// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipFood.API.Data;

#nullable disable

namespace ShipFood.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627032401_AddGiaNhapGiaBan")]
    partial class AddGiaNhapGiaBan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ShipFood.API.Models.TbChiTietDonHang", b =>
                {
                    b.Property<int>("Mactdh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("mactdh");

                    b.Property<decimal>("Dongia")
                        .HasColumnType("TEXT")
                        .HasColumnName("dongia");

                    b.Property<int>("Madh")
                        .HasColumnType("INTEGER")
                        .HasColumnName("madh");

                    b.Property<int>("Mamon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mamon");

                    b.Property<int>("Soluong")
                        .HasColumnType("INTEGER")
                        .HasColumnName("soluong");

                    b.HasKey("Mactdh");

                    b.HasIndex("Madh");

                    b.HasIndex("Mamon");

                    b.ToTable("tbChiTietDonHang");
                });

            modelBuilder.Entity("ShipFood.API.Models.TbDanhMuc", b =>
                {
                    b.Property<int>("Madanhmuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("madanhmuc");

                    b.Property<string>("Hinhanh")
                        .HasColumnType("TEXT")
                        .HasColumnName("hinhanh");

                    b.Property<string>("Mota")
                        .HasColumnType("TEXT")
                        .HasColumnName("mota");

                    b.Property<string>("Tendanhmuc")
                        .HasColumnType("TEXT")
                        .HasColumnName("tendanhmuc");

                    b.HasKey("Madanhmuc");

                    b.ToTable("tbDanhMuc");
                });

            modelBuilder.Entity("ShipFood.API.Models.TbDonHang", b =>
                {
                    b.Property<int>("Madh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("madh");

                    b.Property<string>("Ghichu")
                        .HasColumnType("TEXT")
                        .HasColumnName("ghichu");

                    b.Property<int?>("Mashipper")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mashipper");

                    b.Property<DateTime>("Ngaydathang")
                        .HasColumnType("TEXT")
                        .HasColumnName("ngaydathang");

                    b.Property<decimal>("Phiship")
                        .HasColumnType("TEXT")
                        .HasColumnName("phiship");

                    b.Property<decimal>("Tongtien")
                        .HasColumnType("TEXT")
                        .HasColumnName("tongtien");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trangthai");

                    b.HasKey("Madh");

                    b.ToTable("tbDonHang");
                });

            modelBuilder.Entity("ShipFood.API.Models.TbKhachHang", b =>
                {
                    b.Property<int>("Userid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("userid");

                    b.Property<string>("Tenkh")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenkh");

                    b.HasKey("Userid");

                    b.ToTable("tbKhachHang");
                });

            modelBuilder.Entity("ShipFood.API.Models.TbMonAn", b =>
                {
                    b.Property<int>("Mamon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("mamon");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Giatien")
                        .HasColumnType("TEXT")
                        .HasColumnName("giatien");

                    b.Property<string>("Hinhanh")
                        .HasColumnType("TEXT")
                        .HasColumnName("hinhanh");

                    b.Property<int?>("Madanhmuc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("madanhmuc");

                    b.Property<int?>("Maquanan")
                        .HasColumnType("INTEGER")
                        .HasColumnName("maquanan");

                    b.Property<string>("Mota")
                        .HasColumnType("TEXT")
                        .HasColumnName("mota");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("TEXT")
                        .HasColumnName("ngaytao");

                    b.Property<bool>("Noibat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("noibat");

                    b.Property<int>("Phantramgiam")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phantramgiam");

                    b.Property<int>("Soluongban")
                        .HasColumnType("INTEGER")
                        .HasColumnName("soluongban");

                    b.Property<string>("Tenmon")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenmon");

                    b.HasKey("Mamon");

                    b.ToTable("tbMonAn");
                });

            modelBuilder.Entity("ShipFood.API.Models.TbQuanAn", b =>
                {
                    b.Property<int>("Userid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("userid");

                    b.Property<string>("Diachi")
                        .HasColumnType("TEXT")
                        .HasColumnName("diachi");

                    b.Property<decimal?>("Diemdanhgia")
                        .HasColumnType("TEXT")
                        .HasColumnName("diemdanhgia");

                    b.Property<string>("Hinhanh")
                        .HasColumnType("TEXT")
                        .HasColumnName("hinhanh");

                    b.Property<int?>("Soluotdanhgia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("soluotdanhgia");

                    b.Property<string>("Tenquanan")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenquanan");

                    b.Property<string>("Trangthai")
                        .HasColumnType("TEXT")
                        .HasColumnName("trangthai");

                    b.HasKey("Userid");

                    b.ToTable("tbQuanAn");
                });

            modelBuilder.Entity("ShipFood.API.Models.TbShipper", b =>
                {
                    b.Property<int>("Userid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("userid");

                    b.Property<string>("Diachi")
                        .HasColumnType("TEXT")
                        .HasColumnName("diachi");

                    b.Property<decimal?>("Diemdanhgia")
                        .HasColumnType("TEXT")
                        .HasColumnName("diemdanhgia");

                    b.Property<string>("Hinhanh")
                        .HasColumnType("TEXT")
                        .HasColumnName("hinhanh");

                    b.Property<int?>("Soluotdanhgia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("soluotdanhgia");

                    b.Property<string>("Tenshipper")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenshipper");

                    b.Property<string>("Trangthai")
                        .HasColumnType("TEXT")
                        .HasColumnName("trangthai");

                    b.HasKey("Userid");

                    b.ToTable("tbShipper");
                });

            modelBuilder.Entity("ShipFood.API.Models.TbTonKho", b =>
                {
                    b.Property<int>("MaKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("makho");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mamon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mamon");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("TEXT")
                        .HasColumnName("ngaycapnhat");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("INTEGER")
                        .HasColumnName("soluongnhap");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("soluongton");

                    b.HasKey("MaKho");

                    b.HasIndex("Mamon");

                    b.ToTable("tbTonKho");
                });

            modelBuilder.Entity("ShipFood.API.Models.TbUser", b =>
                {
                    b.Property<int>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("userid");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Loaitaikhoan")
                        .HasColumnType("TEXT")
                        .HasColumnName("loaitaikhoan");

                    b.Property<string>("Pwd")
                        .HasColumnType("TEXT")
                        .HasColumnName("pwd");

                    b.Property<string>("Sdt")
                        .HasColumnType("TEXT")
                        .HasColumnName("sdt");

                    b.Property<int>("Trangthai")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trangthai");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<decimal?>("Vitien")
                        .HasColumnType("TEXT")
                        .HasColumnName("vitien");

                    b.HasKey("Userid");

                    b.ToTable("tbUser");
                });

            modelBuilder.Entity("ShipFood.API.Models.TbVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPercent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TbVoucher");
                });

            modelBuilder.Entity("ShipFood.API.Models.TbChiTietDonHang", b =>
                {
                    b.HasOne("ShipFood.API.Models.TbDonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("Madh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShipFood.API.Models.TbMonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("Mamon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("ShipFood.API.Models.TbKhachHang", b =>
                {
                    b.HasOne("ShipFood.API.Models.TbUser", "TbUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TbUser");
                });

            modelBuilder.Entity("ShipFood.API.Models.TbQuanAn", b =>
                {
                    b.HasOne("ShipFood.API.Models.TbUser", "TbUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TbUser");
                });

            modelBuilder.Entity("ShipFood.API.Models.TbShipper", b =>
                {
                    b.HasOne("ShipFood.API.Models.TbUser", "TbUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TbUser");
                });

            modelBuilder.Entity("ShipFood.API.Models.TbTonKho", b =>
                {
                    b.HasOne("ShipFood.API.Models.TbMonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("Mamon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonAn");
                });
#pragma warning restore 612, 618
        }
    }
}
